language: dart

# necessary to avoid chrome sandboxing issues
sudo: required

# Run against both the dev and stable channel.
dart:
  - stable
  - dev

# Define test tasks to run.
dart_task:
  - test: --platform vm

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

os:
  - windows

cache:
  directories:
    - $HOME/.pub-cache