language: dart

dart:
  - dev

dart_task:
  - test: -p vm,firefox
  - dartanalyzer --fatal-warnings

matrix:
  include:
    - dart: 2.2.0
      dart_task:
        dartanalyzer --fatal-warnings


branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache